# Generated by Django 4.0.1 on 2022-09-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamproduct',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teamproductkit',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
