# Generated by Django 4.1.6 on 2023-06-26 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('offer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleoffer',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saledone',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offer.saleoffer'),
        ),
        migrations.AddField(
            model_name='saledone',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.transaction'),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasedone',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offer.purchaseoffer'),
        ),
        migrations.AddField(
            model_name='purchasedone',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.transaction'),
        ),
    ]
